# Generated by Django 2.0.4 on 2018-04-26 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fandom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FandomCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fanficrawler.Category')),
                ('fandom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fanficrawler.Fandom')),
            ],
        ),
        migrations.CreateModel(
            name='Fanfic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('title', models.CharField(max_length=200)),
                ('sinopse', models.TextField()),
                ('rated', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('ship', models.CharField(max_length=200)),
                ('chapter', models.IntegerField()),
                ('words', models.IntegerField()),
                ('reviews', models.IntegerField()),
                ('favs', models.IntegerField()),
                ('follows', models.IntegerField()),
                ('update', models.DateField()),
                ('published', models.DateField()),
                ('text', models.TextField()),
                ('fandom', models.ManyToManyField(to='fanficrawler.FandomCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Ficwriter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('name', models.CharField(max_length=200)),
                ('joined', models.DateField()),
                ('update', models.DateField()),
                ('country', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='fanfic',
            name='ficwriter',
            field=models.ManyToManyField(to='fanficrawler.Ficwriter'),
        ),
    ]
