# Generated by Django 2.0.4 on 2018-04-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanficrawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='fandom',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='fandomcategory',
            unique_together={('category', 'fandom')},
        ),
    ]
