# Generated by Django 2.0.4 on 2018-04-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanficrawler', '0002_auto_20180426_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanfic',
            name='favs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fanfic',
            name='follows',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fanfic',
            name='reviews',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fanfic',
            name='ship',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='fanfic',
            name='update',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ficwriter',
            name='joined',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ficwriter',
            name='link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ficwriter',
            name='update',
            field=models.DateField(blank=True, null=True),
        ),
    ]
