# Generated by Django 2.0.4 on 2018-04-27 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanficrawler', '0003_auto_20180426_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficwriter',
            name='country',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
