# Generated by Django 2.0.4 on 2018-04-27 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanficrawler', '0004_auto_20180426_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanfic',
            name='genre',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
