# Generated by Django 2.0.4 on 2018-04-27 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanficrawler', '0005_fanfic_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fanfic',
            name='text',
        ),
        migrations.AlterField(
            model_name='fanfic',
            name='chapter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fanfic',
            name='sinopse',
            field=models.TextField(blank=True, default=''),
        ),
    ]
