# Generated by Django 2.0.4 on 2018-04-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanficrawler', '0007_auto_20180426_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanfic',
            name='link',
            field=models.TextField(),
        ),
    ]
