# Generated by Django 2.0.5 on 2018-05-25 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fandom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FandomCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fanfics.Category')),
                ('fandom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fanfics.Fandom')),
            ],
        ),
        migrations.CreateModel(
            name='Fanfic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('title', models.CharField(max_length=200)),
                ('sinopse', models.TextField(blank=True, default='')),
                ('genre', models.CharField(blank=True, default='', max_length=200)),
                ('rated', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('ship', models.CharField(blank=True, default='', max_length=200)),
                ('chapter', models.IntegerField(blank=True, null=True)),
                ('words', models.IntegerField(blank=True, null=True)),
                ('reviews', models.IntegerField(blank=True, null=True)),
                ('favs', models.IntegerField(blank=True, null=True)),
                ('follows', models.IntegerField(blank=True, null=True)),
                ('update', models.DateField(blank=True, null=True)),
                ('published', models.DateField(blank=True, null=True)),
                ('fandom', models.ManyToManyField(to='fanfics.FandomCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Ficwriter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, default='')),
                ('name', models.CharField(max_length=200)),
                ('joined', models.DateField(blank=True, null=True)),
                ('update', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='fanfic',
            name='ficwriter',
            field=models.ManyToManyField(to='fanfics.Ficwriter'),
        ),
        migrations.AlterUniqueTogether(
            name='fandomcategory',
            unique_together={('category', 'fandom')},
        ),
    ]
