# Generated by Django 2.0.5 on 2018-05-25 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanfics', '0002_auto_20180525_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
