# Generated by Django 2.0.5 on 2018-05-25 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanfics', '0004_migrate_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fanfic',
            name='language',
        ),
    ]
