# Generated by Django 2.0.5 on 2018-05-25 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanfics', '0005_remove_fanfic_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fanfic',
            old_name='lang',
            new_name='language',
        ),
    ]
