# Generated by Django 2.0.5 on 2018-05-25 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fanfics', '0006_auto_20180525_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanfic',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fanfics.Language'),
        ),
    ]
