# Generated by Django 2.0.5 on 2018-05-25 02:06

from django.db import migrations

def migrate(apps, schema_editor):
    Fanfic = apps.get_model('fanfics', 'Fanfic')
    Language = apps.get_model('fanfics', 'Language')

    for lang in Language.objects.all():
        correct_name = lang.name.strip()
        if lang.name == correct_name:
            continue
            
        correct_language = Language.objects.get(name=correct_name)
        Fanfic.objects.filter(language=lang).update(language=correct_language)


class Migration(migrations.Migration):

    dependencies = [
        ('fanfics', '0007_auto_20180525_0150'),
    ]

    operations = [
        migrations.RunPython(migrate)
    ]
