# Generated by Django 2.0.5 on 2018-06-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanfics', '0009_remove_invalid_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='fandom',
            name='image_url',
            field=models.URLField(blank=True, default='http://yiibooster.oadoc360.com/images/placeholder260x180.gif'),
        ),
    ]
