# Generated by Django 3.1.2 on 2020-11-01 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanfics', '0010_fandom_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fandom',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='fanfic',
            name='language',
            field=models.TextField(),
        ),
    ]
